owner: tinytoolsllc
repo: status

sites:
  - name: My Release Notes
    url: https://www.myreleasenotes.ai
  - name: My Release Notes API
    url: https://api.myreleasenotes.ai/api/feed

status-website:
  cname: status.myreleasenotes.ai
  name: My Release Notes Status
  introTitle: "**My Release Notes** Status Page"
  introMessage: This is the status page for [My Release Notes](https://www.myreleasenotes.ai), powered by [Upptime](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
